#!/usr/bin/env python3
"""Quick test to verify RBM script creation works"""

from pathlib import Path

# Test the script creation
codebase_path = Path("/Users/sandymacdonald/Documents/Projects/EVALLab/papers/codebases/AIX360")
rbm_metrics_script = codebase_path / 'run_rbm_metrics.py'

rbm_script_content = '''#!/usr/bin/env python3
"""
AIX360 RBM Metrics Extraction Script
Runs the Boolean Rule CG algorithm and outputs metrics in a structured format
Auto-generated by EVALLab
"""

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from aix360.algorithms.rbm import FeatureBinarizer, BRCGExplainer, BooleanRuleCG


def main():
    print("=" * 80)
    print("AIX360 Boolean Rule Column Generation - Metrics Extraction")
    print("=" * 80)
    
    # Load breast cancer dataset
    bc = load_breast_cancer()
    bc_df = pd.DataFrame(bc.data, columns=bc.feature_names)
    
    # Split data
    X_train, X_test, Y_train, Y_test = train_test_split(
        bc_df, bc.target, test_size=0.2, random_state=31
    )
    
    # Feature binarization
    print("\\n[1/3] Feature Binarization...")
    fb = FeatureBinarizer(negations=True)
    X_train_fb = fb.fit_transform(X_train)
    X_test_fb = fb.transform(X_test)
    print(f"  ✓ Training features: {len(X_train_fb.columns)}")
    print(f"  ✓ Test features: {len(X_test_fb.columns)}")
    
    # Train Boolean Rule model
    print("\\n[2/3] Training Boolean Rule Model...")
    boolean_model = BooleanRuleCG(silent=True)
    explainer = BRCGExplainer(boolean_model)
    explainer.fit(X_train_fb, Y_train)
    print("  ✓ Model trained")
    
    # Predict and calculate metrics
    print("\\n[3/3] Evaluating Model...")
    Y_pred = explainer.predict(X_test_fb)
    
    accuracy = accuracy_score(Y_test, Y_pred)
    precision = precision_score(Y_test, Y_pred)
    recall = recall_score(Y_test, Y_pred)
    f1 = f1_score(Y_test, Y_pred)
    
    # Print metrics in structured format for parsing
    print("\\n" + "=" * 80)
    print("METRICS SUMMARY")
    print("=" * 80)
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print("=" * 80)
    
    # Get explanation rules
    explanation = explainer.explain()
    print("\\nLEARNED RULES:")
    for i, rule in enumerate(explanation['rules'], 1):
        print(f"  {i}. {rule}")
    
    print("\\n✓ Metrics extraction complete")
    
    # Return metrics as dict for potential JSON output
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'num_rules': len(explanation['rules']),
        'test_size': len(Y_test),
        'train_size': len(Y_train)
    }


if __name__ == '__main__':
    metrics = main()
'''

try:
    rbm_metrics_script.write_text(rbm_script_content)
    rbm_metrics_script.chmod(0o755)
    print(f"✓ Created: {rbm_metrics_script}")
    print(f"✓ File exists: {rbm_metrics_script.exists()}")
    print(f"✓ File size: {rbm_metrics_script.stat().st_size} bytes")
except Exception as e:
    print(f"✗ Error: {e}")
