def _build_metrics_table_rows(df):
    """
    Build HTML table rows for the metrics comparison table.
    Args:
        df: Pandas DataFrame with comparison results
    Returns:
        HTML string with <tr> rows
    """
    rows = []
    for _, row in df.iterrows():
        diff_class = 'diff-pos' if row['percent_difference'] >= 0 else 'diff-neg'
        status_class = 'status-pass' if row['within_threshold'] else 'status-fail'
        rows.append(
            f"<tr>"
            f"<td>{row['configuration']}</td>"
            f"<td>{row['metric_name']}</td>"
            f"<td>{row['baseline_value']:.4f}</td>"
            f"<td>{row['reproduced_value']:.4f}</td>"
            f"<td class='{diff_class}'>{row['percent_difference']:+.2f}%</td>"
            f"<td class='{status_class}'>{'PASS' if row['within_threshold'] else 'FAIL'}</td>"
            f"</tr>"
        )
    return '\n'.join(rows)

import pandas as pd
import json
import logging
from datetime import datetime
from pathlib import Path


def generate_visualizations_index_html(visualizations_root: Path) -> str:
    """
    Generate a top-level dashboard listing all papers' visualizations.
    """
    visualizations_root = Path(visualizations_root)
    paper_dirs = [d for d in visualizations_root.iterdir() if d.is_dir()]
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>EVALLab Dashboard</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        .paper-list {{ margin: 30px 0; }}
        .paper-entry {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.08); margin: 18px 0; padding: 18px; }}
        .paper-entry h2 {{ margin: 0 0 10px 0; color: #34495e; }}
        .paper-entry a {{ color: #3498db; font-weight: bold; text-decoration: none; }}
        .footer {{ margin-top: 40px; padding: 20px; text-align: center; color: #7f8c8d; border-top: 1px solid #bdc3c7; }}
    </style>
</head>
<body>
    <h1>EVALLab Dashboard</h1>
    <h2>All Papers: EVALLab's Reports</h2>
    <div class="paper-list">
        {''.join([
            f'<div class="paper-entry">'
            f'<h2>Research Paper: {d.name}</h2>'
            f'<a href="{d.name}/visualizations.html">View Visualizations, Metrics & Logs for this research paper</a>'
            f'</div>' for d in paper_dirs if (d / 'visualizations.html').exists()
        ])}
    </div>
    <div class="footer">
        <p>Generated by EVALLab</p>
        <p>Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
</body>
</html>
"""
    return html


def generate_visualization_index_html(files: dict, df: pd.DataFrame, paper_name: str, output_dir: Path = None) -> str:
    """
    Generate an HTML index page for all visualizations, including resource usage and summary metrics.
    """
    runtime_seconds = None
    peak_memory_mb = None
    if output_dir is None:
        if 'overall_performance' in files:
            output_dir = Path(files['overall_performance']).parent
        else:
            output_dir = Path('.')
    try:
        resource_path = output_dir / 'resource_usage.json'
        print(f"[DEBUG] Attempting to read resource usage from: {resource_path}")
        with open(resource_path, 'r') as f:
            usage = json.load(f)
            print(f"[DEBUG] Loaded resource_usage.json contents: {usage}")
            runtime_seconds = usage.get('runtime_seconds')
            peak_memory_mb = usage.get('peak_memory_mb')
        if runtime_seconds is None or peak_memory_mb is None:
            logging.warning(f"resource_usage.json found but contains None values: {usage}")
        else:
            logging.info(f"Loaded resource_usage.json: runtime_seconds={runtime_seconds}, peak_memory_mb={peak_memory_mb}")
    except Exception as e:
        logging.warning(f"Failed to load resource_usage.json: {e}")
        print(f"[DEBUG] Exception while reading resource_usage.json: {e}")
 

    # Metrics summary
    total_comparisons = len(df) if df is not None else 0
    passing = int(df['within_threshold'].sum()) if df is not None and 'within_threshold' in df else 0
    failing = total_comparisons - passing
    success_rate = (passing / total_comparisons * 100) if total_comparisons > 0 else 0
    mean_abs_dev = f"{df['percent_difference'].abs().mean():.2f}%" if df is not None and 'percent_difference' in df else 'N/A'
    median_abs_dev = f"{df['percent_difference'].abs().median():.2f}%" if df is not None and 'percent_difference' in df else 'N/A'
    std_dev = f"{df['percent_difference'].std():.2f}%" if df is not None and 'percent_difference' in df else 'N/A'

    # Style success rate: green >=80%, orange 50-80%, red <50%
    if success_rate >= 80:
        sr_class = 'success-high'
    elif success_rate >= 50:
        sr_class = 'success-mid'
    else:
        sr_class = 'success-low'

    metrics_html = f'''
    <div class="summary">
        <h3>EVALLab Performance Summary</h3>
        <div class="metric"><div><u>Total Metric Comparisons</u></div><div class="metric-value">{total_comparisons}</div></div>
        <div class="metric"><div><u>Passing Metrics</u></div><div class="metric-value status-pass">{passing}</div></div>
        <div class="metric"><div><u>Failing Metrics</u></div><div class="metric-value status-fail">{failing}</div></div>
        <div class="metric"><div><u>Success Rate</u></div><div class="metric-value {sr_class}">{success_rate:.1f}%</div></div>
        <div class="metric"><div><u>Mean Abs. Deviation</u></div><div class="metric-value">{mean_abs_dev}</div></div>
        <div class="metric"><div><u>Median Abs. Deviation</u></div><div class="metric-value">{median_abs_dev}</div></div>
        <div class="metric"><div><u>Std Dev of Deviations</u></div><div class="metric-value">{std_dev}</div></div>
        <div class="metric"><div><u>Total EVALLab Runtime</u></div><div class="metric-value">{'{:.2f} seconds'.format(runtime_seconds) if runtime_seconds is not None else 'N/A'}</div></div>
        <div class="metric"><div><u>Peak EVALLab Memory Usage</u></div><div class="metric-value">{'{:.2f} MB'.format(peak_memory_mb) if peak_memory_mb is not None else 'N/A'}</div></div>
    </div>
    '''

    # Visualizations with captions
    viz_html = ""
    plot_keys = [
        ('overall_performance', 'Overall Performance'),
        ('performance_by_configuration', 'Performance by Configuration'),
        ('baseline_vs_reproduced', 'Baseline vs Reproduced'),
        ('deviation_distribution', 'Deviation Distribution'),
        ('heatmap_granularity_tasktype', 'Success Rate by Granularity and Task Type'),
        ('summary_statistics', 'Summary Statistics'),
    ]
    for key, caption in plot_keys:
        if key in files:
            img_path = files[key].name
            viz_html += f'<div class="viz-section"><h3>{caption}</h3><img src="{img_path}" style="max-width:90%;margin:20px 0;box-shadow:0 2px 8px #ccc;border-radius:8px;"></div>'

    # Metrics Table (color-coded)
    table_html = ""
    if df is not None and not df.empty:
        table_html += '<div class="visualization"><h2>Metric Comparison Table</h2><div class="metrics-table-wrapper"><table class="metrics-table">'
        table_html += '<tr><th>Configuration</th><th>Metric</th><th>Baseline</th><th>Reproduced</th><th>Diff (%)</th><th>Status</th></tr>'
        table_html += _build_metrics_table_rows(df)
        table_html += '</table></div>'
        if 'detailed_csv' in files:
            table_html += f'<a href="{files["detailed_csv"].name}">Download detailed_comparison.csv</a>'
        table_html += '</div>'

    # Agent log
    import html as html_module
    log_html = ""
    if 'agent_log' in files and files['agent_log'].exists():
        try:
            with open(files['agent_log'], 'r', encoding='utf-8') as logf:
                log_content = logf.read()
            log_html = f'''<div class="agent-log"><h3>EVALLab Agent Execution Log for this Research Paper</h3><details style="white-space:pre-wrap; background:#f8f8f8; border:1px solid #ccc; padding:10px; border-radius:6px; max-height:400px; overflow:auto;"><summary>Show/Hide Agent Log</summary><pre style="font-family: 'Fira Mono', 'Consolas', 'Menlo', 'monospace'; font-size: 15px; white-space: pre; background: #222; color: #eee; border-radius: 6px; padding: 12px; overflow-x: auto;">{html_module.escape(log_content)}</pre></details></div>'''
        except Exception as e:
            log_html = f'<div class="agent-log"><b>Could not load agent log: {e}</b></div>'

    # Footer
    from datetime import datetime
    footer_html = f'''<div class="footer"><p>Generated by EVALLab</p><p>Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p></div>'''

    # Compose full HTML
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>EVALLab .Reproducibility Analysis - {paper_name}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0 auto; padding: 20px; background-color: #f5f5f5; }}
            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #34495e; margin-top: 30px; }}
            .summary {{ background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 20px 0; text-align: center; }}
            .metric {{ display: inline-block; margin: 10px 20px 10px 0; font-size: 18px; vertical-align: top; text-align: center; }}
            .metric-value {{ font-weight: bold; color: #3498db; font-size: 24px; }}
            .status-pass {{ color: #27ae60; font-weight: bold; }}
            .status-fail {{ color: #e74c3c; font-weight: bold; }}
            .success-high {{ color: #27ae60; font-weight: bold; }}
            .success-mid {{ color: #e67e22; font-weight: bold; }}
            .success-low {{ color: #e74c3c; font-weight: bold; }}
            .diff-pos {{ color: #2980b9; }}
            .diff-neg {{ color: #e67e22; }}
            .viz-section {{ margin: 30px 0; text-align: center; }}
            .metrics-table-wrapper {{ overflow-x: auto; }}
            .metrics-table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            .metrics-table th, .metrics-table td {{ border: 1px solid #ccc; padding: 8px 12px; text-align: center; }}
            .metrics-table th {{ background: #eaf1fb; }}
            .metrics-table tr:nth-child(even) {{ background: #f9f9f9; }}
            .agent-log {{ margin: 40px 0; }}
            .footer {{ margin-top: 40px; padding: 20px; text-align: center; color: #7f8c8d; border-top: 1px solid #bdc3c7; }}
        </style>
    </head>
    <body>
        <a href="../visualizations.html" style="display:inline-block; margin:16px 0 0 0; color:#3498db; text-decoration:none; font-size:16px;">Back to EVALLab Dashboard</a>
        <h1>EVALLab's Research Paper Reproducibility Analysis</h1>
        <h2>Research Paper: {paper_name}</h2>
        {metrics_html}
        {viz_html}
        {table_html}
        {log_html}
        {footer_html}
    </body>
    </html>
    """
    return html
